/*
 * StringInputDialog.java
 *
 * Created on 18 aprile 2004, 14.33
 */

package com.ost.timekeeper.ui;

import com.ost.timekeeper.util.*;

/**
 *
 * @author  davide
 */
public class StringInputDialog extends javax.swing.JDialog {
	
	private String titleText;
	private String labelText;
	
	/** Creates new form StringInputDialog */
	public StringInputDialog(java.awt.Frame parent, String title, String label, boolean modal) {
		super(parent, modal);
		initComponents();
		this.titleText = title;
		this.labelText = label;
		postInitComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {
        jPanelDescription = new javax.swing.JPanel();
//        jLabelDescription = new javax.swing.JLabel();
        jTextFieldInput = new javax.swing.JTextField();
        jPanelData = new javax.swing.JPanel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanelDescription.setLayout(new java.awt.BorderLayout());

//        jLabelDescription.setText("Input data");
//        jPanelDescription.add(jLabelDescription, java.awt.BorderLayout.NORTH);

        jTextFieldInput.setText("");
        jPanelDescription.add(jTextFieldInput, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelDescription, java.awt.BorderLayout.CENTER);

        jButtonConfirm.setText(ResourceSupplier.getString (ResourceClass.UI, "global", "controls.button.confirm"));
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelData.add(jButtonConfirm);

        jButtonCancel.setText(ResourceSupplier.getString (ResourceClass.UI, "global", "controls.button.cancel"));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanelData.add(jButtonCancel);

        getContentPane().add(jPanelData, java.awt.BorderLayout.SOUTH);

        pack();
    }

	private void postInitComponents() {
		jPanelDescription.setBorder(new javax.swing.border.TitledBorder (this.labelText));
//		this.jLabelDescription.setText(this.labelText);
		this.setTitle(this.titleText);
		this.pack();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// Add your handling code here:
		this.hide ();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// Add your handling code here:
		this.hide();
	}
	
	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt) {
		setVisible(false);
		dispose();
	}
	
    // Variables declaration - do not modify
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonCancel;
//    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JPanel jPanelDescription;
    private javax.swing.JPanel jPanelData;
    private javax.swing.JTextField jTextFieldInput;
    // End of variables declaration
	
	public static String createDialog (java.awt.Frame parent, String tile, String label, boolean modal){
		StringInputDialog dialog = new StringInputDialog (parent, tile, label, modal);
        dialog.pack();
		dialog.show ();
		return dialog.jTextFieldInput.getText();
	}
}
