/*
 * JFrame.java
 *
 * Created on 26 dicembre 2005, 10.53
 */

package com.davidecavestro.rbe.gui;

import java.awt.*;
import org.jdesktop.swingx.*;
import org.jdesktop.swingx.decorator.*;

/**
 *
 * @author  davide
 */
public class JFrame extends javax.swing.JFrame {
	
	/** Creates new form JFrame */
	public JFrame () {
		initComponents ();
		
		
//		Highlighter[]   highlighters = new Highlighter[] {
//			new AlternateRowHighlighter (Color.white,
//			new Color (0xF0, 0xF0, 0xE0), null),
//			new PatternHighlighter (null, Color.red, "^s", 0, 0)
//		};
//		
//		HighlighterPipeline highlighterPipeline = new HighlighterPipeline (highlighters);
//		jTable1.setHighlighters (highlighterPipeline);
		
		
//		SearchHighlighter sh = new SearchHighlighter (null, Color.yellow);
//		sh.setEnabled (true);
//		Highlighter[]   highlighters = new Highlighter[] {
///*
//			new AlternateRowHighlighter (Color.white,
//			new Color (0xF0, 0xF0, 0xE0), null),
// */
////			new PatternHighlighter (null, Color.red, "^s", 0, 0)
//			sh
//			
//		};
//		HighlighterPipeline highlighterPipeline = new HighlighterPipeline(highlighters);
//		jTable1.setHighlighters (highlighterPipeline);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTable1 = new JXTable ();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        getContentPane().add(jTable1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

	private void jMenu1ActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_jMenu1ActionPerformed
	
	/** Exit the Application */
	private void exitForm (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit (0);
	}//GEN-LAST:event_exitForm
	
	/**
	 * @param args the command line arguments
	 */
	public static void main (String args[]) {
		new JFrame ().show ();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
	
}
