/*
 * Splash.java
 *
 * Created on 20 gennaio 2006, 23.58
 */

package com.davidecavestro.rbe.gui;

import com.davidecavestro.common.application.ApplicationData;
import com.davidecavestro.rbe.ApplicationContext;

/**
 *
 * @author  davide
 */
public class Splash extends javax.swing.JFrame {
	
	private final ApplicationData _appData;
	
		
	/** Costruttore.*/
	public Splash ( ApplicationData appData) {
		this._appData = appData;
		initComponents ();
		pack ();
		/*
		 * Centra sullo schermo.
		 */
		setLocationRelativeTo (null);
		
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        progressBar = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        applicationImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("com.davidecavestro.rbe.gui.res").getString("Loading_application..."));
        setName("splashFrame");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getAccessibleContext().setAccessibleName("splashFrame");
        getAccessibleContext().setAccessibleDescription("Application startup splash");
        progressBar.setValue(99);
        progressBar.setIndeterminate(true);
        getContentPane().add(progressBar, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2));
        appNameLabel.setFont(new java.awt.Font("Impact", 1, 66));
        appNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(appNameLabel, _appData.getApplicationExternalName ());
        appNameLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(appNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 180, 90));

        appVersionLabel.setFont(new java.awt.Font("Impact", 1, 32));
        appVersionLabel.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(appVersionLabel, _appData.getVersionNumber ());
        appVersionLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(appVersionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 2, 70, 85));

        applicationImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        applicationImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/davidecavestro/rbe/gui/images/splash.png")));
        applicationImageLabel.setIconTextGap(-220);
        jPanel1.add(applicationImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
	
	/** Exit the Application */
	private void exitForm (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit (0);
	}//GEN-LAST:event_exitForm
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JLabel applicationImageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

	/**
	 * Mostra le informazioni passate.
	 *
	 * @param info le informazioni.
	 */	
	public void showInfo (String info){
		this.applicationImageLabel.setText (info);
	}
}
