/*
 * Splash.java
 *
 * Created on 20 gennaio 2006, 23.58
 */

package com.davidecavestro.rbe.gui;

/**
 *
 * @author  davide
 */
public class Splash extends javax.swing.JFrame {
	
	/** Creates new form Splash */
	public Splash () {
		initComponents ();
		pack ();
		/*
		 * Centra sullo schermo.
		 */
		setLocationRelativeTo (null);
		
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents() {//GEN-BEGIN:initComponents
        applicationImageLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("com.davidecavestro.rbe.gui.res").getString("Loading_application..."));
        setName("splashFrame");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getAccessibleContext().setAccessibleName("splashFrame");
        getAccessibleContext().setAccessibleDescription("Application startup splash");
        applicationImageLabel.setForeground(new java.awt.Color(255, 255, 255));
        applicationImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/davidecavestro/rbe/gui/images/splash.png")));
        applicationImageLabel.setIconTextGap(-220);
        getContentPane().add(applicationImageLabel, java.awt.BorderLayout.CENTER);

        progressBar.setValue(99);
        progressBar.setIndeterminate(true);
        getContentPane().add(progressBar, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
	
	/** Exit the Application */
	private void exitForm (java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
		System.exit (0);
	}//GEN-LAST:event_exitForm
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applicationImageLabel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

	/**
	 * Mostra le informazioni passate.
	 *
	 * @param info le informazioni.
	 */	
	public void showInfo (String info){
		this.applicationImageLabel.setText (info);
	}
}
